version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: go-showcase-mongo

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: go_showcase

    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: go-showcase-api

    ports:
      - "8080:8080"

    environment:
      PORT: "8080"
      MONGO_URI: "mongodb://mongo:27017"
      MONGO_DATABASE: "go_showcase"
      MONGO_TIMEOUT_SECONDS: "10"

    depends_on:
      - mongo

volumes:
  mongo-data: